export type FileKind = "html" | "css" | "js" | "md" | "binary";

export interface ProjectFile {
  kind: FileKind;
  code?: string;
  meta?: string;
}

const SCRIPT_OPEN = "<scr" + "ipt";
const SCRIPT_CLOSE = "</scr" + "ipt>";

export const FILES: Record<string, ProjectFile> = {
  "index.html": {
    kind: "html",
    code: [
      '<!DOCTYPE html>',
      '<html lang="en">',
      '<head>',
      '  <meta charset="utf-8">',
      '  <meta name="viewport" content="width=device-width, initial-scale=1">',
      '  <title>Studio \u2014 Web prototype</title>',
      '  <link rel="stylesheet" href="style.css">',
      '</head>',
      '<body>',
      '  <header class="nav" data-nav>',
      '    <a class="nav__brand" href="#top">Studio</a>',
      '    <nav class="nav__links">',
      '      <a href="#work">Work</a>',
      '      <a href="#about">About</a>',
      '      <a href="#contact">Contact</a>',
      '    </nav>',
      '    <button class="nav__toggle" aria-label="Menu">Menu</button>',
      '  </header>',
      '',
      '  <main>',
      '    <section class="hero" id="top">',
      '      <h1 class="hero__title">We build calm interfaces.</h1>',
      '      <p class="hero__lede">Twelve years of product work, no theatrics.</p>',
      '      <a class="btn" href="#work">See the work</a>',
      '    </section>',
      '',
      '    <section class="showcase" id="work" data-reveal>',
      '      <article class="card"><h3>Ledger</h3><p>Finance ops, rebuilt.</p></article>',
      '      <article class="card"><h3>Atlas</h3><p>Maps for field teams.</p></article>',
      '      <article class="card"><h3>Pique</h3><p>Editorial CMS.</p></article>',
      '    </section>',
      '  </main>',
      '',
      '  <footer class="foot">',
      '    <small>&copy; 2026 Studio. All rights reserved.</small>',
      '  </footer>',
      '',
      '  ' + SCRIPT_OPEN + ' src="script.js">' + SCRIPT_CLOSE,
      '</body>',
      '</html>'
    ].join("\n")
  },
  "style.css": {
    kind: "css",
    code: [
      ':root {',
      '  --paper: #faf8f4;',
      '  --ink: #12161c;',
      '  --muted: #657485;',
      '  --line: #ddd7c9;',
      '  --brand: #1f4463;',
      '}',
      '',
      '* { box-sizing: border-box; }',
      '',
      'body {',
      '  margin: 0;',
      '  background: var(--paper);',
      '  color: var(--ink);',
      '  font-family: Inter, system-ui, sans-serif;',
      '  line-height: 1.55;',
      '}',
      '',
      '.nav {',
      '  position: sticky;',
      '  top: 0;',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 24px;',
      '  padding: 16px 32px;',
      '  border-bottom: 1px solid var(--line);',
      '}',
      '',
      '.nav__links { display: flex; gap: 20px; margin-left: auto; }',
      '.nav__links a { color: var(--muted); text-decoration: none; }',
      '.nav__links a:hover { color: var(--brand); }',
      '',
      '.hero { padding: 96px 32px 64px; max-width: 720px; }',
      '.hero__title { font-size: 48px; letter-spacing: -0.02em; margin: 0 0 12px; }',
      '.hero__lede { color: var(--muted); margin: 0 0 28px; }',
      '',
      '.showcase {',
      '  display: grid;',
      '  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));',
      '  gap: 16px;',
      '  padding: 0 32px 96px;',
      '}',
      '',
      '.card {',
      '  padding: 20px;',
      '  background: #fff;',
      '  border: 1px solid var(--line);',
      '  border-radius: 10px;',
      '  transition: transform 120ms ease;',
      '}',
      '',
      '.card:hover { transform: translateY(-2px); }',
      '',
      '@media (max-width: 640px) {',
      '  .nav__links { display: none; }',
      '  .hero__title { font-size: 32px; }',
      '}'
    ].join("\n")
  },
  "script.js": {
    kind: "js",
    code: [
      '(function () {',
      '  "use strict";',
      '',
      '  const select = (sel, root) => (root || document).querySelector(sel);',
      '  const selectAll = (sel, root) => Array.from((root || document).querySelectorAll(sel));',
      '',
      '  function initNavbar() {',
      '    const nav = select("[data-nav]");',
      '    if (!nav) return;',
      '    let last = window.scrollY;',
      '    window.addEventListener("scroll", () => {',
      '      const y = window.scrollY;',
      '      nav.dataset.state = y > last && y > 120 ? "hidden" : "shown";',
      '      last = y;',
      '    }, { passive: true });',
      '  }',
      '',
      '  function initMobileMenu() {',
      '    const toggle = select(".nav__toggle");',
      '    const links = select(".nav__links");',
      '    if (!toggle || !links) return;',
      '    toggle.addEventListener("click", () => links.classList.toggle("is-open"));',
      '  }',
      '',
      '  function initReveals() {',
      '    const targets = selectAll("[data-reveal]");',
      '    const io = new IntersectionObserver((entries) => {',
      '      entries.forEach((entry) => {',
      '        if (!entry.isIntersecting) return;',
      '        entry.target.classList.add("is-visible");',
      '        io.unobserve(entry.target);',
      '      });',
      '    }, { threshold: 0.2 });',
      '    targets.forEach((t) => io.observe(t));',
      '  }',
      '',
      '  function initAnchorScroll() {',
      '    selectAll("a[href]").forEach((link) => {',
      '      link.addEventListener("click", (event) => {',
      '        const target = select(link.getAttribute("href"));',
      '        if (!target) return;',
      '        event.preventDefault();',
      '        window.scrollTo({ top: target.offsetTop - 72, behavior: "smooth" });',
      '      });',
      '    });',
      '  }',
      '',
      '  function initIcons() {',
      '    selectAll("[data-icon]").forEach((node) => {',
      '      node.setAttribute("stroke-width", "1.6");',
      '      node.setAttribute("width", "16");',
      '      node.setAttribute("height", "16");',
      '    });',
      '  }',
      '',
      '  function init() {',
      '    initNavbar();',
      '    initMobileMenu();',
      '    initReveals();',
      '    initAnchorScroll();',
      '    initIcons();',
      '  }',
      '',
      '  let resizeTimer;',
      '  window.addEventListener("resize", () => {',
      '    clearTimeout(resizeTimer);',
      '    resizeTimer = setTimeout(initReveals, 200);',
      '  });',
      '',
      '  if (document.readyState === "loading") {',
      '    document.addEventListener("DOMContentLoaded", init);',
      '  } else {',
      '    init();',
      '  }',
      '})();'
    ].join("\n")
  },
  "logo.svg": {
    kind: "html",
    code: [
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none">',
      '  <title>Studio mark</title>',
      '  <rect x="2" y="2" width="28" height="28" rx="7" stroke="#1f4463" stroke-width="2"/>',
      '  <path d="M10 21V11h5.5a3.5 3.5 0 0 1 0 7H10" stroke="#1f4463" stroke-width="2"/>',
      '  <circle cx="22" cy="12" r="1.6" fill="#1f4463"/>',
      '</svg>'
    ].join("\n")
  },
  "readme.md": {
    kind: "md",
    code: [
      '# Studio \u2014 web prototype',
      '',
      'A three-file static prototype. No build step, no dependencies.',
      '',
      '## Files',
      '',
      '- `index.html` \u2014 markup and section order',
      '- `style.css` \u2014 tokens, layout, responsive rules',
      '- `script.js` \u2014 nav, reveals, anchor scroll, icon normalisation',
      '',
      '## Running it',
      '',
      'Copy the three files into one folder and open `index.html`.',
      'No server is required; the reveal observer works from the file protocol.',
      '',
      '## Icon system',
      '',
      'All glyphs come from a single stroke set, 16px optical size, 1.6px stroke.',
      'Do not mix in glyphs from other sets \u2014 see the note in `style.css`.',
      '',
      '## Conventions',
      '',
      '1. Every colour is a token in `:root`, never a literal in a rule.',
      '2. Breakpoints: 640px and 1024px only.',
      '3. Motion stays under 200ms, ease only.'
    ].join("\n")
  },
  "hero.webp": { kind: "binary", meta: "1600 \u00d7 900 \u00b7 148 KB \u00b7 image/webp" }
};

export interface TreeNode {
  name: string;
  type: "folder" | "file";
  children?: string[];
}

export const TREE: TreeNode[] = [
  { name: "src", type: "folder", children: ["index.html", "style.css", "script.js"] },
  { name: "assets", type: "folder", children: ["logo.svg", "hero.webp"] },
  { name: "readme.md", type: "file" }
];
